name: JMeter Performance Test

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  jmeter-test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: JMeter Test
        uses: QAInsights/PerfAction@v5.6.2
        with:
          test-plan-path: './Test.jmx'
          args: ""
          
      - name: Upload Results
        uses: actions/upload-artifact@v4
        with:
          name: jmeter-results
          path: result.jtl
          if-no-files-found: error
